### ISSUE TITLE
Help wanted?

### ISSUE THREAD

**Issue by calebmer** [cksac/graphql-rs#1]
I and a colleague @svmnotn have also been working on a GraphQL parser which is just bindings to [`libgraphqlparser`](https://github.com/graphql/libgraphqlparser). We believe your approach will be more performant and easier/more enjoyable to write and maintain. Therefore we'd like to offer our assistance in the development of this library.

Would this be something you want? If so, how can we help?

**Comment by cksac** [comment]
@calebmer any help would be appreciated. If you would like to continue work on the parser, you may create a pull request for it.

**Comment by calebmer** [comment]
Awesome! We'll try to start helping some time this week 😊
